CREATE DATABASE IF NOT EXISTS OFICINA_SAEP_BD;
USE OFICINA_SAEP_BD;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(100) NOT NULL,
    USU_SENHA VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS VEICULO(
	VEI_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEI_MODELO VARCHAR(100) NOT NULL,
    VEI_ANO VARCHAR(4) NOT NULL,
    VEI_MARCA VARCHAR(100) NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FOREIGN KEY(FK_CLI_ID) REFERENCES CLIENTE(CLI_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AGENDAMENTO(
	AGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    AGE_DATA_HORA DATETIME NOT NULL,
    AGE_MOTIVO VARCHAR(100) NOT NULL,
    AGE_STATUS VARCHAR(30) NOT NULL,
    FK_VEI_ID INT NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FOREIGN KEY(FK_CLI_ID) REFERENCES CLIENTE(CLI_ID) ON DELETE CASCADE,
    FOREIGN KEY(FK_VEI_ID) REFERENCES VEICULO(VEI_ID) ON DELETE CASCADE
);

INSERT INTO USUARIO(USU_NOME, USU_EMAIL, USU_SENHA)
VALUES("Admin","admin@admin.com", "admin123"),
	  ("Usuario 1","usuario@1.com", "123456"),
      ("Usuario 2","usuario@2.com", "123456");
      
INSERT INTO CLIENTE(CLI_NOME, CLI_DATA_NASCIMENTO)
VALUES("Cliente 1","1944-03-10"), -- 1
	  ("Cliente 2","2005-10-12"), -- 2
      ("Cliente 3", "2006-11-11"); -- 3
      
INSERT INTO VEICULO(VEI_MODELO, VEI_ANO, VEI_MARCA, FK_CLI_ID)
VALUES("Fusion","2006", "Ford", 1), -- cliente 1
	  ("Santana", "2000", "Volkswagen", 2), -- cliente 2
      ("Astra", "2010", "Chevrolet", 3); -- cliente 3
      
INSERT INTO AGENDAMENTO(AGE_DATA_HORA, AGE_MOTIVO, AGE_STATUS, FK_VEI_ID, FK_CLI_ID)
VALUES("2026-09-29 08:00:00","Vazamento de óleo", "Agendada", 1, 1), -- fusion
	  ("2026-09-29 09:00:00","Problema na bateria", "Agendada", 2, 2), -- santana
      ("2026-09-29 23:00:00","Lataria amassada", "Agendada", 3, 3); -- astra
      